### ISSUE TITLE
我魔怔了

### ISSUE THREAD

**Issue by Minghou-Lei** [Majie-Chen/JVM-Study#1]
入门到入魔👍👍👍

**Comment by Majie-Chen** [comment]
这么闲




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Majie-Chen/JVM-Study"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月30日(星期五) 下午2:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Majie-Chen/JVM-Study] 我魔怔了 (#1)





 
入门到入魔👍👍👍

**Comment by Minghou-Lei** [comment]
还用Email回复，高级

**Comment by Majie-Chen** [comment]
向杨戈学习





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Majie-Chen/JVM-Study"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月30日(星期五) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Majie-Chen/JVM-Study] 我魔怔了 (#1)





 
还用Email回复，高级
